# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='板块名', max_length=20)),
                ('parent', models.IntegerField(help_text='上级目录')),
                ('grade', models.IntegerField(help_text='级别')),
            ],
        ),
    ]
